//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Contacto = new HashSet<Contacto>();
        }
    
        public int ID { get; set; }
        public string Carg { get; set; }
    
        public virtual ICollection<Contacto> Contacto { get; set; }
    }
}
