//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public Contacto()
        {
            this.TelefonoContacto = new HashSet<TelefonoContacto>();
            this.Cargo = new HashSet<Cargo>();
        }
    
        public int ID { get; set; }
        public int IDEmpresa { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<TelefonoContacto> TelefonoContacto { get; set; }
        public virtual ICollection<Cargo> Cargo { get; set; }
    }
}
