//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Direccion()
        {
            this.DireccionContacto = new HashSet<DireccionContacto>();
            this.Empresa = new HashSet<Empresa>();
        }
    
        public int ID { get; set; }
        public string Domicilio { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string CP { get; set; }
    
        public virtual ICollection<DireccionContacto> DireccionContacto { get; set; }
        public virtual ICollection<Empresa> Empresa { get; set; }
    }
}
