//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDCRMEntities : DbContext
    {
        public BDCRMEntities()
            : base("name=BDCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionComercial> AccionComercial { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Direccion> Direccion { get; set; }
        public virtual DbSet<DireccionContacto> DireccionContacto { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<TelefonoContacto> TelefonoContacto { get; set; }
        public virtual DbSet<TelefonoEmpresa> TelefonoEmpresa { get; set; }
        public virtual DbSet<TipoAccion> TipoAccion { get; set; }
        public virtual DbSet<TipoEmpresa> TipoEmpresa { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
