//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelefonoContacto
    {
        public int IDContacto { get; set; }
        public string Telefono { get; set; }
    
        public virtual Contacto Contacto { get; set; }
    }
}
