//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes.ServicioDatos2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsuario {
            get {
                return this.IDUsuarioField;
            }
            set {
                if ((this.IDUsuarioField.Equals(value) != true)) {
                    this.IDUsuarioField = value;
                    this.RaisePropertyChanged("IDUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class EmpresaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIF {
            get {
                return this.CIFField;
            }
            set {
                if ((object.ReferenceEquals(this.CIFField, value) != true)) {
                    this.CIFField = value;
                    this.RaisePropertyChanged("CIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTipoEmpresa {
            get {
                return this.IDTipoEmpresaField;
            }
            set {
                if ((this.IDTipoEmpresaField.Equals(value) != true)) {
                    this.IDTipoEmpresaField = value;
                    this.RaisePropertyChanged("IDTipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEmpresa {
            get {
                return this.TipoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEmpresaField, value) != true)) {
                    this.TipoEmpresaField = value;
                    this.RaisePropertyChanged("TipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionComercialData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class AccionComercialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDAccion {
            get {
                return this.IDAccionField;
            }
            set {
                if ((this.IDAccionField.Equals(value) != true)) {
                    this.IDAccionField = value;
                    this.RaisePropertyChanged("IDAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpresa {
            get {
                return this.IDEmpresaField;
            }
            set {
                if ((this.IDEmpresaField.Equals(value) != true)) {
                    this.IDEmpresaField = value;
                    this.RaisePropertyChanged("IDEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEstado {
            get {
                return this.IDEstadoField;
            }
            set {
                if ((this.IDEstadoField.Equals(value) != true)) {
                    this.IDEstadoField = value;
                    this.RaisePropertyChanged("IDEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEmpresaData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TipoEmpresaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonosData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TelefonosData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAccionData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TipoAccionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactoData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class ContactoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCargo {
            get {
                return this.IDCargoField;
            }
            set {
                if ((this.IDCargoField.Equals(value) != true)) {
                    this.IDCargoField = value;
                    this.RaisePropertyChanged("IDCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpresa {
            get {
                return this.IDEmpresaField;
            }
            set {
                if ((this.IDEmpresaField.Equals(value) != true)) {
                    this.IDEmpresaField = value;
                    this.RaisePropertyChanged("IDEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargoData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class CargoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstadoData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class EstadoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DireccionData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class DireccionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomicilioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoblacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CP {
            get {
                return this.CPField;
            }
            set {
                if ((object.ReferenceEquals(this.CPField, value) != true)) {
                    this.CPField = value;
                    this.RaisePropertyChanged("CP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domicilio {
            get {
                return this.DomicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicilioField, value) != true)) {
                    this.DomicilioField = value;
                    this.RaisePropertyChanged("Domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Poblacion {
            get {
                return this.PoblacionField;
            }
            set {
                if ((object.ReferenceEquals(this.PoblacionField, value) != true)) {
                    this.PoblacionField = value;
                    this.RaisePropertyChanged("Poblacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDatos2.ISrvDatos")]
    public interface ISrvDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllUsers", ReplyAction="http://tempuri.org/ISrvDatos/GetAllUsersResponse")]
        Clientes.ServicioDatos2.UserData[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllUsers", ReplyAction="http://tempuri.org/ISrvDatos/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEmpresas", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEmpresasResponse")]
        Clientes.ServicioDatos2.EmpresaData[] GetAllEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEmpresas", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEmpresasResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData[]> GetAllEmpresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComerciales", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesResponse")]
        Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComerciales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComerciales", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposEmpresaResponse")]
        Clientes.ServicioDatos2.TipoEmpresaData[] GetAllTiposEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData[]> GetAllTiposEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresaResponse")]
        Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosEmpresa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosEmpresaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosContactoResponse")]
        Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosContacto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosContactoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosContactoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposAccionResponse")]
        Clientes.ServicioDatos2.TipoAccionData[] GetAllTiposAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposAccionResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData[]> GetAllTiposAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosEmpresaResponse")]
        Clientes.ServicioDatos2.ContactoData[] GetAllContactosEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosResponse")]
        Clientes.ServicioDatos2.CargoData[] GetAllCargos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosContactoResponse")]
        Clientes.ServicioDatos2.CargoData[] GetAllCargosContacto(int contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosContactoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosContactoAsync(int contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetEmpresaResponse")]
        Clientes.ServicioDatos2.EmpresaData GetEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData> GetEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditEmpresaResponse")]
        bool EditEmpresa(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditEmpresaResponse")]
        System.Threading.Tasks.Task<bool> EditEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddEmpresaResponse")]
        int AddEmpresa(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddEmpresaResponse")]
        System.Threading.Tasks.Task<int> AddEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarEmpresaResponse")]
        bool BorrarEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarEmpresaResponse")]
        System.Threading.Tasks.Task<bool> BorrarEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddTipoEmpresaResponse")]
        int AddTipoEmpresa(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddTipoEmpresaResponse")]
        System.Threading.Tasks.Task<int> AddTipoEmpresaAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTipoEmpresaResponse")]
        bool BorrarTipoEmpresa(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTipoEmpresaResponse")]
        System.Threading.Tasks.Task<bool> BorrarTipoEmpresaAsync(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/AddTipoAccionResponse")]
        int AddTipoAccion(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/AddTipoAccionResponse")]
        System.Threading.Tasks.Task<int> AddTipoAccionAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTipoAccionResponse")]
        bool BorrarTipoAccion(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTipoAccionResponse")]
        System.Threading.Tasks.Task<bool> BorrarTipoAccionAsync(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTelefonoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddTelefonoEmpresaResponse")]
        bool AddTelefonoEmpresa(Clientes.ServicioDatos2.TelefonosData telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTelefonoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddTelefonoEmpresaResponse")]
        System.Threading.Tasks.Task<bool> AddTelefonoEmpresaAsync(Clientes.ServicioDatos2.TelefonosData telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTelefonoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTelefonoEmpresaResponse")]
        bool BorrarTelefonoEmpresa(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTelefonoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTelefonoEmpresaResponse")]
        System.Threading.Tasks.Task<bool> BorrarTelefonoEmpresaAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTelefonoContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddTelefonoContactoResponse")]
        bool AddTelefonoContacto(Clientes.ServicioDatos2.TelefonosData telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddTelefonoContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddTelefonoContactoResponse")]
        System.Threading.Tasks.Task<bool> AddTelefonoContactoAsync(Clientes.ServicioDatos2.TelefonosData telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTelefonoContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTelefonoContactoResponse")]
        bool BorrarTelefonoContacto(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarTelefonoContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarTelefonoContactoResponse")]
        System.Threading.Tasks.Task<bool> BorrarTelefonoContactoAsync(string telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddUser", ReplyAction="http://tempuri.org/ISrvDatos/AddUserResponse")]
        int AddUser(Clientes.ServicioDatos2.UserData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddUser", ReplyAction="http://tempuri.org/ISrvDatos/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(Clientes.ServicioDatos2.UserData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarUser", ReplyAction="http://tempuri.org/ISrvDatos/BorrarUserResponse")]
        bool BorrarUser(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarUser", ReplyAction="http://tempuri.org/ISrvDatos/BorrarUserResponse")]
        System.Threading.Tasks.Task<bool> BorrarUserAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditUser", ReplyAction="http://tempuri.org/ISrvDatos/EditUserResponse")]
        bool EditUser(Clientes.ServicioDatos2.UserData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditUser", ReplyAction="http://tempuri.org/ISrvDatos/EditUserResponse")]
        System.Threading.Tasks.Task<bool> EditUserAsync(Clientes.ServicioDatos2.UserData user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetUser", ReplyAction="http://tempuri.org/ISrvDatos/GetUserResponse")]
        Clientes.ServicioDatos2.UserData GetUser(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetUser", ReplyAction="http://tempuri.org/ISrvDatos/GetUserResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData> GetUserAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetContactoResponse")]
        Clientes.ServicioDatos2.ContactoData GetContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetContactoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData> GetContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosResponse")]
        Clientes.ServicioDatos2.ContactoData[] GetAllContactos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddContactoResponse")]
        int AddContacto(Clientes.ServicioDatos2.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddContactoResponse")]
        System.Threading.Tasks.Task<int> AddContactoAsync(Clientes.ServicioDatos2.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarContactoResponse")]
        bool BorrarContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarContactoResponse")]
        System.Threading.Tasks.Task<bool> BorrarContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditContacto", ReplyAction="http://tempuri.org/ISrvDatos/EditContactoResponse")]
        bool EditContacto(Clientes.ServicioDatos2.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditContacto", ReplyAction="http://tempuri.org/ISrvDatos/EditContactoResponse")]
        System.Threading.Tasks.Task<bool> EditContactoAsync(Clientes.ServicioDatos2.ContactoData contacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/GetAccionComercialResponse")]
        Clientes.ServicioDatos2.AccionComercialData GetAccionComercial(int idAccionComercial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/GetAccionComercialResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData> GetAccionComercialAsync(int idAccionComercial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/AddAccionComercialResponse")]
        int AddAccionComercial(Clientes.ServicioDatos2.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/AddAccionComercialResponse")]
        System.Threading.Tasks.Task<int> AddAccionComercialAsync(Clientes.ServicioDatos2.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/BorrarAccionComercialResponse")]
        bool BorrarAccionComercial(int idaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/BorrarAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> BorrarAccionComercialAsync(int idaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/EditAccionComercialResponse")]
        bool EditAccionComercial(Clientes.ServicioDatos2.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditAccionComercial", ReplyAction="http://tempuri.org/ISrvDatos/EditAccionComercialResponse")]
        System.Threading.Tasks.Task<bool> EditAccionComercialAsync(Clientes.ServicioDatos2.AccionComercialData accion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesEmpresaResponse")]
        Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComercialesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesUsuario", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesUsuarioResponse")]
        Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComercialesUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesUsuario", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesUsuarioResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEstados", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEstadosResponse")]
        Clientes.ServicioDatos2.EstadoData[] GetAllEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEstados", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEstadosResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EstadoData[]> GetAllEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEstado", ReplyAction="http://tempuri.org/ISrvDatos/AddEstadoResponse")]
        int AddEstado(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEstado", ReplyAction="http://tempuri.org/ISrvDatos/AddEstadoResponse")]
        System.Threading.Tasks.Task<int> AddEstadoAsync(string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarEstado", ReplyAction="http://tempuri.org/ISrvDatos/BorrarEstadoResponse")]
        bool BorrarEstado(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarEstado", ReplyAction="http://tempuri.org/ISrvDatos/BorrarEstadoResponse")]
        System.Threading.Tasks.Task<bool> BorrarEstadoAsync(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddCargo", ReplyAction="http://tempuri.org/ISrvDatos/AddCargoResponse")]
        int AddCargo(string cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddCargo", ReplyAction="http://tempuri.org/ISrvDatos/AddCargoResponse")]
        System.Threading.Tasks.Task<int> AddCargoAsync(string cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarCargo", ReplyAction="http://tempuri.org/ISrvDatos/BorrarCargoResponse")]
        bool BorrarCargo(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarCargo", ReplyAction="http://tempuri.org/ISrvDatos/BorrarCargoResponse")]
        System.Threading.Tasks.Task<bool> BorrarCargoAsync(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllDireccionesEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllDireccionesEmpresaResponse")]
        Clientes.ServicioDatos2.DireccionData[] GetAllDireccionesEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllDireccionesEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllDireccionesEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData[]> GetAllDireccionesEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllDireccionesContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllDireccionesContactoResponse")]
        Clientes.ServicioDatos2.DireccionData[] GetAllDireccionesContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllDireccionesContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllDireccionesContactoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData[]> GetAllDireccionesContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetDireccion", ReplyAction="http://tempuri.org/ISrvDatos/GetDireccionResponse")]
        Clientes.ServicioDatos2.DireccionData GetDireccion(int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetDireccion", ReplyAction="http://tempuri.org/ISrvDatos/GetDireccionResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData> GetDireccionAsync(int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccion", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionResponse")]
        int AddDireccion(Clientes.ServicioDatos2.DireccionData direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccion", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionResponse")]
        System.Threading.Tasks.Task<int> AddDireccionAsync(Clientes.ServicioDatos2.DireccionData direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditDireccion", ReplyAction="http://tempuri.org/ISrvDatos/EditDireccionResponse")]
        bool EditDireccion(Clientes.ServicioDatos2.DireccionData direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditDireccion", ReplyAction="http://tempuri.org/ISrvDatos/EditDireccionResponse")]
        System.Threading.Tasks.Task<bool> EditDireccionAsync(Clientes.ServicioDatos2.DireccionData direccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccion", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionResponse")]
        bool BorrarDireccion(int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccion", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionResponse")]
        System.Threading.Tasks.Task<bool> BorrarDireccionAsync(int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccionEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionEmpresaResponse")]
        int AddDireccionEmpresa(Clientes.ServicioDatos2.DireccionData direccion, int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccionEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionEmpresaResponse")]
        System.Threading.Tasks.Task<int> AddDireccionEmpresaAsync(Clientes.ServicioDatos2.DireccionData direccion, int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccionContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionContactoResponse")]
        int AddDireccionContacto(Clientes.ServicioDatos2.DireccionData direccion, int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddDireccionContacto", ReplyAction="http://tempuri.org/ISrvDatos/AddDireccionContactoResponse")]
        System.Threading.Tasks.Task<int> AddDireccionContactoAsync(Clientes.ServicioDatos2.DireccionData direccion, int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccionEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionEmpresaResponse")]
        bool BorrarDireccionEmpresa(int idEmpresa, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccionEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionEmpresaResponse")]
        System.Threading.Tasks.Task<bool> BorrarDireccionEmpresaAsync(int idEmpresa, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccionContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionContactoResponse")]
        bool BorrarDireccionContacto(int idContacto, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/BorrarDireccionContacto", ReplyAction="http://tempuri.org/ISrvDatos/BorrarDireccionContactoResponse")]
        System.Threading.Tasks.Task<bool> BorrarDireccionContactoAsync(int idContacto, int idDireccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditTipoEmpresaResponse")]
        bool EditTipoEmpresa(Clientes.ServicioDatos2.TipoEmpresaData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditTipoEmpresaResponse")]
        System.Threading.Tasks.Task<bool> EditTipoEmpresaAsync(Clientes.ServicioDatos2.TipoEmpresaData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetTipoEmpresaResponse")]
        Clientes.ServicioDatos2.TipoEmpresaData GetTipoEmpresa(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetTipoEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetTipoEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData> GetTipoEmpresaAsync(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/EditTipoAccionResponse")]
        bool EditTipoAccion(Clientes.ServicioDatos2.TipoAccionData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/EditTipoAccionResponse")]
        System.Threading.Tasks.Task<bool> EditTipoAccionAsync(Clientes.ServicioDatos2.TipoAccionData tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetTipoAccionResponse")]
        Clientes.ServicioDatos2.TipoAccionData GetTipoAccion(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetTipoAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetTipoAccionResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData> GetTipoAccionAsync(int idTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditCargo", ReplyAction="http://tempuri.org/ISrvDatos/EditCargoResponse")]
        bool EditCargo(Clientes.ServicioDatos2.CargoData cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditCargo", ReplyAction="http://tempuri.org/ISrvDatos/EditCargoResponse")]
        System.Threading.Tasks.Task<bool> EditCargoAsync(Clientes.ServicioDatos2.CargoData cargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetCargo", ReplyAction="http://tempuri.org/ISrvDatos/GetCargoResponse")]
        Clientes.ServicioDatos2.CargoData GetCargo(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetCargo", ReplyAction="http://tempuri.org/ISrvDatos/GetCargoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData> GetCargoAsync(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEstado", ReplyAction="http://tempuri.org/ISrvDatos/EditEstadoResponse")]
        bool EditEstado(Clientes.ServicioDatos2.EstadoData estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEstado", ReplyAction="http://tempuri.org/ISrvDatos/EditEstadoResponse")]
        System.Threading.Tasks.Task<bool> EditEstadoAsync(Clientes.ServicioDatos2.EstadoData estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEstado", ReplyAction="http://tempuri.org/ISrvDatos/GetEstadoResponse")]
        Clientes.ServicioDatos2.EstadoData GetEstado(int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEstado", ReplyAction="http://tempuri.org/ISrvDatos/GetEstadoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EstadoData> GetEstadoAsync(int idEstado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvDatosChannel : Clientes.ServicioDatos2.ISrvDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvDatosClient : System.ServiceModel.ClientBase<Clientes.ServicioDatos2.ISrvDatos>, Clientes.ServicioDatos2.ISrvDatos {
        
        public SrvDatosClient() {
        }
        
        public SrvDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clientes.ServicioDatos2.UserData[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public Clientes.ServicioDatos2.EmpresaData[] GetAllEmpresas() {
            return base.Channel.GetAllEmpresas();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData[]> GetAllEmpresasAsync() {
            return base.Channel.GetAllEmpresasAsync();
        }
        
        public Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComerciales() {
            return base.Channel.GetAllAccionesComerciales();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesAsync() {
            return base.Channel.GetAllAccionesComercialesAsync();
        }
        
        public Clientes.ServicioDatos2.TipoEmpresaData[] GetAllTiposEmpresa() {
            return base.Channel.GetAllTiposEmpresa();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData[]> GetAllTiposEmpresaAsync() {
            return base.Channel.GetAllTiposEmpresaAsync();
        }
        
        public Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosEmpresa(int id) {
            return base.Channel.GetAllTelefonosEmpresa(id);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosEmpresaAsync(int id) {
            return base.Channel.GetAllTelefonosEmpresaAsync(id);
        }
        
        public Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosContacto(int id) {
            return base.Channel.GetAllTelefonosContacto(id);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosContactoAsync(int id) {
            return base.Channel.GetAllTelefonosContactoAsync(id);
        }
        
        public Clientes.ServicioDatos2.TipoAccionData[] GetAllTiposAccion() {
            return base.Channel.GetAllTiposAccion();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData[]> GetAllTiposAccionAsync() {
            return base.Channel.GetAllTiposAccionAsync();
        }
        
        public Clientes.ServicioDatos2.ContactoData[] GetAllContactosEmpresa(int idEmpresa) {
            return base.Channel.GetAllContactosEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosEmpresaAsync(int idEmpresa) {
            return base.Channel.GetAllContactosEmpresaAsync(idEmpresa);
        }
        
        public Clientes.ServicioDatos2.CargoData[] GetAllCargos() {
            return base.Channel.GetAllCargos();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosAsync() {
            return base.Channel.GetAllCargosAsync();
        }
        
        public Clientes.ServicioDatos2.CargoData[] GetAllCargosContacto(int contacto) {
            return base.Channel.GetAllCargosContacto(contacto);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosContactoAsync(int contacto) {
            return base.Channel.GetAllCargosContactoAsync(contacto);
        }
        
        public Clientes.ServicioDatos2.EmpresaData GetEmpresa(int idEmpresa) {
            return base.Channel.GetEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData> GetEmpresaAsync(int idEmpresa) {
            return base.Channel.GetEmpresaAsync(idEmpresa);
        }
        
        public bool EditEmpresa(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.EditEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<bool> EditEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.EditEmpresaAsync(empresa);
        }
        
        public int AddEmpresa(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.AddEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<int> AddEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.AddEmpresaAsync(empresa);
        }
        
        public bool BorrarEmpresa(int idEmpresa) {
            return base.Channel.BorrarEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarEmpresaAsync(int idEmpresa) {
            return base.Channel.BorrarEmpresaAsync(idEmpresa);
        }
        
        public int AddTipoEmpresa(string tipo) {
            return base.Channel.AddTipoEmpresa(tipo);
        }
        
        public System.Threading.Tasks.Task<int> AddTipoEmpresaAsync(string tipo) {
            return base.Channel.AddTipoEmpresaAsync(tipo);
        }
        
        public bool BorrarTipoEmpresa(int idTipo) {
            return base.Channel.BorrarTipoEmpresa(idTipo);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarTipoEmpresaAsync(int idTipo) {
            return base.Channel.BorrarTipoEmpresaAsync(idTipo);
        }
        
        public int AddTipoAccion(string tipo) {
            return base.Channel.AddTipoAccion(tipo);
        }
        
        public System.Threading.Tasks.Task<int> AddTipoAccionAsync(string tipo) {
            return base.Channel.AddTipoAccionAsync(tipo);
        }
        
        public bool BorrarTipoAccion(int idTipo) {
            return base.Channel.BorrarTipoAccion(idTipo);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarTipoAccionAsync(int idTipo) {
            return base.Channel.BorrarTipoAccionAsync(idTipo);
        }
        
        public bool AddTelefonoEmpresa(Clientes.ServicioDatos2.TelefonosData telefono) {
            return base.Channel.AddTelefonoEmpresa(telefono);
        }
        
        public System.Threading.Tasks.Task<bool> AddTelefonoEmpresaAsync(Clientes.ServicioDatos2.TelefonosData telefono) {
            return base.Channel.AddTelefonoEmpresaAsync(telefono);
        }
        
        public bool BorrarTelefonoEmpresa(string telefono) {
            return base.Channel.BorrarTelefonoEmpresa(telefono);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarTelefonoEmpresaAsync(string telefono) {
            return base.Channel.BorrarTelefonoEmpresaAsync(telefono);
        }
        
        public bool AddTelefonoContacto(Clientes.ServicioDatos2.TelefonosData telefono) {
            return base.Channel.AddTelefonoContacto(telefono);
        }
        
        public System.Threading.Tasks.Task<bool> AddTelefonoContactoAsync(Clientes.ServicioDatos2.TelefonosData telefono) {
            return base.Channel.AddTelefonoContactoAsync(telefono);
        }
        
        public bool BorrarTelefonoContacto(string telefono) {
            return base.Channel.BorrarTelefonoContacto(telefono);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarTelefonoContactoAsync(string telefono) {
            return base.Channel.BorrarTelefonoContactoAsync(telefono);
        }
        
        public int AddUser(Clientes.ServicioDatos2.UserData user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(Clientes.ServicioDatos2.UserData user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public bool BorrarUser(int idUsuario) {
            return base.Channel.BorrarUser(idUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarUserAsync(int idUsuario) {
            return base.Channel.BorrarUserAsync(idUsuario);
        }
        
        public bool EditUser(Clientes.ServicioDatos2.UserData user) {
            return base.Channel.EditUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> EditUserAsync(Clientes.ServicioDatos2.UserData user) {
            return base.Channel.EditUserAsync(user);
        }
        
        public Clientes.ServicioDatos2.UserData GetUser(int idUsuario) {
            return base.Channel.GetUser(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData> GetUserAsync(int idUsuario) {
            return base.Channel.GetUserAsync(idUsuario);
        }
        
        public Clientes.ServicioDatos2.ContactoData GetContacto(int idContacto) {
            return base.Channel.GetContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData> GetContactoAsync(int idContacto) {
            return base.Channel.GetContactoAsync(idContacto);
        }
        
        public Clientes.ServicioDatos2.ContactoData[] GetAllContactos() {
            return base.Channel.GetAllContactos();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosAsync() {
            return base.Channel.GetAllContactosAsync();
        }
        
        public int AddContacto(Clientes.ServicioDatos2.ContactoData contacto) {
            return base.Channel.AddContacto(contacto);
        }
        
        public System.Threading.Tasks.Task<int> AddContactoAsync(Clientes.ServicioDatos2.ContactoData contacto) {
            return base.Channel.AddContactoAsync(contacto);
        }
        
        public bool BorrarContacto(int idContacto) {
            return base.Channel.BorrarContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarContactoAsync(int idContacto) {
            return base.Channel.BorrarContactoAsync(idContacto);
        }
        
        public bool EditContacto(Clientes.ServicioDatos2.ContactoData contacto) {
            return base.Channel.EditContacto(contacto);
        }
        
        public System.Threading.Tasks.Task<bool> EditContactoAsync(Clientes.ServicioDatos2.ContactoData contacto) {
            return base.Channel.EditContactoAsync(contacto);
        }
        
        public Clientes.ServicioDatos2.AccionComercialData GetAccionComercial(int idAccionComercial) {
            return base.Channel.GetAccionComercial(idAccionComercial);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData> GetAccionComercialAsync(int idAccionComercial) {
            return base.Channel.GetAccionComercialAsync(idAccionComercial);
        }
        
        public int AddAccionComercial(Clientes.ServicioDatos2.AccionComercialData accion) {
            return base.Channel.AddAccionComercial(accion);
        }
        
        public System.Threading.Tasks.Task<int> AddAccionComercialAsync(Clientes.ServicioDatos2.AccionComercialData accion) {
            return base.Channel.AddAccionComercialAsync(accion);
        }
        
        public bool BorrarAccionComercial(int idaccion) {
            return base.Channel.BorrarAccionComercial(idaccion);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarAccionComercialAsync(int idaccion) {
            return base.Channel.BorrarAccionComercialAsync(idaccion);
        }
        
        public bool EditAccionComercial(Clientes.ServicioDatos2.AccionComercialData accion) {
            return base.Channel.EditAccionComercial(accion);
        }
        
        public System.Threading.Tasks.Task<bool> EditAccionComercialAsync(Clientes.ServicioDatos2.AccionComercialData accion) {
            return base.Channel.EditAccionComercialAsync(accion);
        }
        
        public Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComercialesEmpresa(int idEmpresa) {
            return base.Channel.GetAllAccionesComercialesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesEmpresaAsync(int idEmpresa) {
            return base.Channel.GetAllAccionesComercialesEmpresaAsync(idEmpresa);
        }
        
        public Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComercialesUsuario(int idUsuario) {
            return base.Channel.GetAllAccionesComercialesUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesUsuarioAsync(int idUsuario) {
            return base.Channel.GetAllAccionesComercialesUsuarioAsync(idUsuario);
        }
        
        public Clientes.ServicioDatos2.EstadoData[] GetAllEstados() {
            return base.Channel.GetAllEstados();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EstadoData[]> GetAllEstadosAsync() {
            return base.Channel.GetAllEstadosAsync();
        }
        
        public int AddEstado(string estado) {
            return base.Channel.AddEstado(estado);
        }
        
        public System.Threading.Tasks.Task<int> AddEstadoAsync(string estado) {
            return base.Channel.AddEstadoAsync(estado);
        }
        
        public bool BorrarEstado(int idEstado) {
            return base.Channel.BorrarEstado(idEstado);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarEstadoAsync(int idEstado) {
            return base.Channel.BorrarEstadoAsync(idEstado);
        }
        
        public int AddCargo(string cargo) {
            return base.Channel.AddCargo(cargo);
        }
        
        public System.Threading.Tasks.Task<int> AddCargoAsync(string cargo) {
            return base.Channel.AddCargoAsync(cargo);
        }
        
        public bool BorrarCargo(int idCargo) {
            return base.Channel.BorrarCargo(idCargo);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarCargoAsync(int idCargo) {
            return base.Channel.BorrarCargoAsync(idCargo);
        }
        
        public Clientes.ServicioDatos2.DireccionData[] GetAllDireccionesEmpresa(int idEmpresa) {
            return base.Channel.GetAllDireccionesEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData[]> GetAllDireccionesEmpresaAsync(int idEmpresa) {
            return base.Channel.GetAllDireccionesEmpresaAsync(idEmpresa);
        }
        
        public Clientes.ServicioDatos2.DireccionData[] GetAllDireccionesContacto(int idContacto) {
            return base.Channel.GetAllDireccionesContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData[]> GetAllDireccionesContactoAsync(int idContacto) {
            return base.Channel.GetAllDireccionesContactoAsync(idContacto);
        }
        
        public Clientes.ServicioDatos2.DireccionData GetDireccion(int idDireccion) {
            return base.Channel.GetDireccion(idDireccion);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.DireccionData> GetDireccionAsync(int idDireccion) {
            return base.Channel.GetDireccionAsync(idDireccion);
        }
        
        public int AddDireccion(Clientes.ServicioDatos2.DireccionData direccion) {
            return base.Channel.AddDireccion(direccion);
        }
        
        public System.Threading.Tasks.Task<int> AddDireccionAsync(Clientes.ServicioDatos2.DireccionData direccion) {
            return base.Channel.AddDireccionAsync(direccion);
        }
        
        public bool EditDireccion(Clientes.ServicioDatos2.DireccionData direccion) {
            return base.Channel.EditDireccion(direccion);
        }
        
        public System.Threading.Tasks.Task<bool> EditDireccionAsync(Clientes.ServicioDatos2.DireccionData direccion) {
            return base.Channel.EditDireccionAsync(direccion);
        }
        
        public bool BorrarDireccion(int idDireccion) {
            return base.Channel.BorrarDireccion(idDireccion);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarDireccionAsync(int idDireccion) {
            return base.Channel.BorrarDireccionAsync(idDireccion);
        }
        
        public int AddDireccionEmpresa(Clientes.ServicioDatos2.DireccionData direccion, int idEmpresa) {
            return base.Channel.AddDireccionEmpresa(direccion, idEmpresa);
        }
        
        public System.Threading.Tasks.Task<int> AddDireccionEmpresaAsync(Clientes.ServicioDatos2.DireccionData direccion, int idEmpresa) {
            return base.Channel.AddDireccionEmpresaAsync(direccion, idEmpresa);
        }
        
        public int AddDireccionContacto(Clientes.ServicioDatos2.DireccionData direccion, int idContacto) {
            return base.Channel.AddDireccionContacto(direccion, idContacto);
        }
        
        public System.Threading.Tasks.Task<int> AddDireccionContactoAsync(Clientes.ServicioDatos2.DireccionData direccion, int idContacto) {
            return base.Channel.AddDireccionContactoAsync(direccion, idContacto);
        }
        
        public bool BorrarDireccionEmpresa(int idEmpresa, int idDireccion) {
            return base.Channel.BorrarDireccionEmpresa(idEmpresa, idDireccion);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarDireccionEmpresaAsync(int idEmpresa, int idDireccion) {
            return base.Channel.BorrarDireccionEmpresaAsync(idEmpresa, idDireccion);
        }
        
        public bool BorrarDireccionContacto(int idContacto, int idDireccion) {
            return base.Channel.BorrarDireccionContacto(idContacto, idDireccion);
        }
        
        public System.Threading.Tasks.Task<bool> BorrarDireccionContactoAsync(int idContacto, int idDireccion) {
            return base.Channel.BorrarDireccionContactoAsync(idContacto, idDireccion);
        }
        
        public bool EditTipoEmpresa(Clientes.ServicioDatos2.TipoEmpresaData tipo) {
            return base.Channel.EditTipoEmpresa(tipo);
        }
        
        public System.Threading.Tasks.Task<bool> EditTipoEmpresaAsync(Clientes.ServicioDatos2.TipoEmpresaData tipo) {
            return base.Channel.EditTipoEmpresaAsync(tipo);
        }
        
        public Clientes.ServicioDatos2.TipoEmpresaData GetTipoEmpresa(int idTipo) {
            return base.Channel.GetTipoEmpresa(idTipo);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData> GetTipoEmpresaAsync(int idTipo) {
            return base.Channel.GetTipoEmpresaAsync(idTipo);
        }
        
        public bool EditTipoAccion(Clientes.ServicioDatos2.TipoAccionData tipo) {
            return base.Channel.EditTipoAccion(tipo);
        }
        
        public System.Threading.Tasks.Task<bool> EditTipoAccionAsync(Clientes.ServicioDatos2.TipoAccionData tipo) {
            return base.Channel.EditTipoAccionAsync(tipo);
        }
        
        public Clientes.ServicioDatos2.TipoAccionData GetTipoAccion(int idTipo) {
            return base.Channel.GetTipoAccion(idTipo);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData> GetTipoAccionAsync(int idTipo) {
            return base.Channel.GetTipoAccionAsync(idTipo);
        }
        
        public bool EditCargo(Clientes.ServicioDatos2.CargoData cargo) {
            return base.Channel.EditCargo(cargo);
        }
        
        public System.Threading.Tasks.Task<bool> EditCargoAsync(Clientes.ServicioDatos2.CargoData cargo) {
            return base.Channel.EditCargoAsync(cargo);
        }
        
        public Clientes.ServicioDatos2.CargoData GetCargo(int idCargo) {
            return base.Channel.GetCargo(idCargo);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData> GetCargoAsync(int idCargo) {
            return base.Channel.GetCargoAsync(idCargo);
        }
        
        public bool EditEstado(Clientes.ServicioDatos2.EstadoData estado) {
            return base.Channel.EditEstado(estado);
        }
        
        public System.Threading.Tasks.Task<bool> EditEstadoAsync(Clientes.ServicioDatos2.EstadoData estado) {
            return base.Channel.EditEstadoAsync(estado);
        }
        
        public Clientes.ServicioDatos2.EstadoData GetEstado(int idEstado) {
            return base.Channel.GetEstado(idEstado);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EstadoData> GetEstadoAsync(int idEstado) {
            return base.Channel.GetEstadoAsync(idEstado);
        }
    }
}
