//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes.ServicioDatos2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class UserData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsuario {
            get {
                return this.IDUsuarioField;
            }
            set {
                if ((this.IDUsuarioField.Equals(value) != true)) {
                    this.IDUsuarioField = value;
                    this.RaisePropertyChanged("IDUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpresaData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class EmpresaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIF {
            get {
                return this.CIFField;
            }
            set {
                if ((object.ReferenceEquals(this.CIFField, value) != true)) {
                    this.CIFField = value;
                    this.RaisePropertyChanged("CIF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTipoEmpresa {
            get {
                return this.IDTipoEmpresaField;
            }
            set {
                if ((this.IDTipoEmpresaField.Equals(value) != true)) {
                    this.IDTipoEmpresaField = value;
                    this.RaisePropertyChanged("IDTipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoEmpresa {
            get {
                return this.TipoEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoEmpresaField, value) != true)) {
                    this.TipoEmpresaField = value;
                    this.RaisePropertyChanged("TipoEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccionComercialData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class AccionComercialData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComentariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comentarios {
            get {
                return this.ComentariosField;
            }
            set {
                if ((object.ReferenceEquals(this.ComentariosField, value) != true)) {
                    this.ComentariosField = value;
                    this.RaisePropertyChanged("Comentarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDAccion {
            get {
                return this.IDAccionField;
            }
            set {
                if ((this.IDAccionField.Equals(value) != true)) {
                    this.IDAccionField = value;
                    this.RaisePropertyChanged("IDAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpresa {
            get {
                return this.IDEmpresaField;
            }
            set {
                if ((this.IDEmpresaField.Equals(value) != true)) {
                    this.IDEmpresaField = value;
                    this.RaisePropertyChanged("IDEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEstado {
            get {
                return this.IDEstadoField;
            }
            set {
                if ((this.IDEstadoField.Equals(value) != true)) {
                    this.IDEstadoField = value;
                    this.RaisePropertyChanged("IDEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((this.UsuarioField.Equals(value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEmpresaData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TipoEmpresaData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TelefonosData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TelefonosData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoAccionData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class TipoAccionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactoData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class ContactoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpresa {
            get {
                return this.IDEmpresaField;
            }
            set {
                if ((this.IDEmpresaField.Equals(value) != true)) {
                    this.IDEmpresaField = value;
                    this.RaisePropertyChanged("IDEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CargoData", Namespace="http://schemas.datacontract.org/2004/07/almerimatik.ServicioCRM")]
    [System.SerializableAttribute()]
    public partial class CargoData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cargo {
            get {
                return this.CargoField;
            }
            set {
                if ((object.ReferenceEquals(this.CargoField, value) != true)) {
                    this.CargoField = value;
                    this.RaisePropertyChanged("Cargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDatos2.ISrvDatos")]
    public interface ISrvDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllUsers", ReplyAction="http://tempuri.org/ISrvDatos/GetAllUsersResponse")]
        Clientes.ServicioDatos2.UserData[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllUsers", ReplyAction="http://tempuri.org/ISrvDatos/GetAllUsersResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEmpresas", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEmpresasResponse")]
        Clientes.ServicioDatos2.EmpresaData[] GetAllEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllEmpresas", ReplyAction="http://tempuri.org/ISrvDatos/GetAllEmpresasResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData[]> GetAllEmpresasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComerciales", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesResponse")]
        Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComerciales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllAccionesComerciales", ReplyAction="http://tempuri.org/ISrvDatos/GetAllAccionesComercialesResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposEmpresaResponse")]
        Clientes.ServicioDatos2.TipoEmpresaData[] GetAllTiposEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData[]> GetAllTiposEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresaResponse")]
        Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosEmpresa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosEmpresaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosContactoResponse")]
        Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosContacto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTelefonosContacto", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTelefonosContactoResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosContactoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposAccionResponse")]
        Clientes.ServicioDatos2.TipoAccionData[] GetAllTiposAccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllTiposAccion", ReplyAction="http://tempuri.org/ISrvDatos/GetAllTiposAccionResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData[]> GetAllTiposAccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosResponse")]
        Clientes.ServicioDatos2.ContactoData[] GetAllContactos(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllContactos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllContactosResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosResponse")]
        Clientes.ServicioDatos2.CargoData[] GetAllCargos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetAllCargos", ReplyAction="http://tempuri.org/ISrvDatos/GetAllCargosResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetEmpresaResponse")]
        Clientes.ServicioDatos2.EmpresaData GetEmpresa(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/GetEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/GetEmpresaResponse")]
        System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData> GetEmpresaAsync(int idEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditEmpresaResponse")]
        bool EditEmpresa(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/EditEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/EditEmpresaResponse")]
        System.Threading.Tasks.Task<bool> EditEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddEmpresaResponse")]
        bool AddEmpresa(Clientes.ServicioDatos2.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISrvDatos/AddEmpresa", ReplyAction="http://tempuri.org/ISrvDatos/AddEmpresaResponse")]
        System.Threading.Tasks.Task<bool> AddEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISrvDatosChannel : Clientes.ServicioDatos2.ISrvDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SrvDatosClient : System.ServiceModel.ClientBase<Clientes.ServicioDatos2.ISrvDatos>, Clientes.ServicioDatos2.ISrvDatos {
        
        public SrvDatosClient() {
        }
        
        public SrvDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SrvDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SrvDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clientes.ServicioDatos2.UserData[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.UserData[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public Clientes.ServicioDatos2.EmpresaData[] GetAllEmpresas() {
            return base.Channel.GetAllEmpresas();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData[]> GetAllEmpresasAsync() {
            return base.Channel.GetAllEmpresasAsync();
        }
        
        public Clientes.ServicioDatos2.AccionComercialData[] GetAllAccionesComerciales() {
            return base.Channel.GetAllAccionesComerciales();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.AccionComercialData[]> GetAllAccionesComercialesAsync() {
            return base.Channel.GetAllAccionesComercialesAsync();
        }
        
        public Clientes.ServicioDatos2.TipoEmpresaData[] GetAllTiposEmpresa() {
            return base.Channel.GetAllTiposEmpresa();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoEmpresaData[]> GetAllTiposEmpresaAsync() {
            return base.Channel.GetAllTiposEmpresaAsync();
        }
        
        public Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosEmpresa(int id) {
            return base.Channel.GetAllTelefonosEmpresa(id);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosEmpresaAsync(int id) {
            return base.Channel.GetAllTelefonosEmpresaAsync(id);
        }
        
        public Clientes.ServicioDatos2.TelefonosData[] GetAllTelefonosContacto(int id) {
            return base.Channel.GetAllTelefonosContacto(id);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TelefonosData[]> GetAllTelefonosContactoAsync(int id) {
            return base.Channel.GetAllTelefonosContactoAsync(id);
        }
        
        public Clientes.ServicioDatos2.TipoAccionData[] GetAllTiposAccion() {
            return base.Channel.GetAllTiposAccion();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.TipoAccionData[]> GetAllTiposAccionAsync() {
            return base.Channel.GetAllTiposAccionAsync();
        }
        
        public Clientes.ServicioDatos2.ContactoData[] GetAllContactos(int idEmpresa) {
            return base.Channel.GetAllContactos(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.ContactoData[]> GetAllContactosAsync(int idEmpresa) {
            return base.Channel.GetAllContactosAsync(idEmpresa);
        }
        
        public Clientes.ServicioDatos2.CargoData[] GetAllCargos() {
            return base.Channel.GetAllCargos();
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.CargoData[]> GetAllCargosAsync() {
            return base.Channel.GetAllCargosAsync();
        }
        
        public Clientes.ServicioDatos2.EmpresaData GetEmpresa(int idEmpresa) {
            return base.Channel.GetEmpresa(idEmpresa);
        }
        
        public System.Threading.Tasks.Task<Clientes.ServicioDatos2.EmpresaData> GetEmpresaAsync(int idEmpresa) {
            return base.Channel.GetEmpresaAsync(idEmpresa);
        }
        
        public bool EditEmpresa(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.EditEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<bool> EditEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.EditEmpresaAsync(empresa);
        }
        
        public bool AddEmpresa(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.AddEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task<bool> AddEmpresaAsync(Clientes.ServicioDatos2.EmpresaData empresa) {
            return base.Channel.AddEmpresaAsync(empresa);
        }
    }
}
